before_script:
  - apt-get update
  - apt install -y make git
  # needed to download NuGet
  - apt-get install -y curl

stages:
  - unit_tests

stockmono_test_unit:
  image: ubuntu:20.04
  stage: unit_tests
  script:
    - source ./scripts/install_regtest_dependencies.sh

    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y mono-complete mono-xbuild fsharp
    - mono --version

    - apt-get install -y nunit-console
    - ./configure.sh
    - make
    - make check-end-to-end

newmono_test_unit:
  image: ubuntu:20.04
  stage: unit_tests
  script:
    - source ./scripts/install_regtest_dependencies.sh
    - ./scripts/install_mono_from_microsoft_deb_packages.sh

    - apt install -y nunit-console

    - time (./configure.sh && make && make check-end-to-end)
